version: "3.8"
services:
  php:
    build: .
    command: symfony server:start --port=80
    working_dir: /local/app
    volumes:
      - .:/local/app
    ports:
      - ${PORT_HTTP:-8888}:80

  mysql:
    image: mysql:8.0.25
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${PORT_MYSQL:-3306}:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password

volumes:
  mysql_data:
